yeastprotien <- read_excel("E:/kamagyana/Computing/DARET/Assignments/yeastprotien.xlsx")
View(yeastprotien)
str(yeastprotien)
table(yeastprotien$class)
nrow(yeastprotien)
tail(yeastprotien)
yeastprotien <- yeastprotien[-c(1485),]
tail(yeastprotien)
nrow(yeastprotien)
table(yeastprotien$class)
sum(is.na(yeastprotien))
sum(is.na(yeastprotien))
library(dplyr)
library(sqldf)
library(ggplot2)
classnuc <- yeastprotien %>% select(nuc,class)
head(classnuc)
str(classnuc)
class(classnuc)
ggplot(yeastprotien,aes(class,nuc)) + geom_boxplot()
result <- aov(nuc~class,data=classnuc);
summary(result)
library(Hmisc)
TukeyHSD(result)
plot(result,1)
library(car)
leveneTest(nuc ~ class, data = classnuc)
oneway.test(nuc ~ class, data = classnuc)
plot(results,2)
plot(result,2)
residuals <- residuals(object = result)
shapiro.test(x = residuals)
kruskal.test(nuc~class,data=classnuc)
str(classnuc)
classnuc$class <- as.factor(classnuc$class)
kruskal.test(nuc~class,data=classnuc)


